version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: JobApplicationDb
      POSTGRES_USER: ${ADMIN_USERNAME}
      POSTGRES_PASSWORD: ${ADMIN_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ./JobApplicationProject
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=JobApplicationDb;Username=${ADMIN_USERNAME};Password=${ADMIN_PASSWORD}
      ASPNETCORE_ENVIRONMENT: Development

volumes:
  pgdata: 